# Generated by Django 3.2.4 on 2021-07-01 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210630_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivo',
            name='idCorrel',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
