# Generated by Django 3.2.4 on 2021-07-08 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_dispositivo_idcorrel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('idMarca', models.IntegerField(db_column='idMarca', primary_key=True, serialize=False)),
                ('nomMarca', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'marca',
            },
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='rutt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.usuario'),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='marcaa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.marca'),
        ),
    ]
